version: "3.3"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  keycloak:
    image:  quay.io/keycloak/keycloak:12.0.1
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
